### ISSUE TITLE
No way to stop calibration?

### ISSUE THREAD

**Issue by jfrux** [qdrk/fpvsim-timer-app#1]

**Comment by qdrk** [comment]
Thanks for flagging. I met this too, it's caused by unstable connection with the timer hardware. Did you use a router as bridge and use 5.8G Wifi?

**Comment by qdrk** [comment]
FYI: this is fixed in the latest [2.2.0-rc5](https://github.com/qdrk/fpvsim-timer-app/releases/tag/2.2.0-rc5)
